### PR TITLE
final notebook

### PR DESCRIPTION
**Pull request by jacksonianrtaylor**
This is the notebook that will be used for the final submission after we review and edit it

### CODE REVIEW

**Comment by 101nazrin** [comment]
Entire code looks good.It would be better if we could add a markdown about the isolation_forest method for outlier detection and comment the code block .The binning strategies have made the data more suitable for modeling.

**Comment by jacksonianrtaylor** [comment]
I am going to implement basic outlier handling on certain columns before applying log and cube root transformations because that is the logical order of things. We can change the outlier detection methods from a range of methods we have implemented in this notebook when we start exploring model development.

**Comment by gvaryani** [comment]
The final notebook looks good to me, ensure that the heading should in bold.

**Comment by gvaryani** [comment]
The final notebook looks good, after implementing the headings.

Thank you!

**Pull request merged**
